---
application:
  name: "ims-server-api"
  project: "demo"
  organization: "QoveryCommunity"
routers:
- name: "main-ims-server-api"
  routes:
  - application_name: "ims-server-api"
    paths:
    - "/*"
